### PR TITLE
Feature/41442 activate screen 20.04 cleanup

### PR DESCRIPTION
**Pull request by magenta-mfm**
Update the script to use the snap's chromedriver as suggested here:
https://github.com/OS2borgerPC/server_image/pull/10

### CODE REVIEW

**Review by magenta-af — CHANGES_REQUESTED** [review]
I've tested this on a fresh OS2displayPC installation and it looks fine, with one caveat - it failed the first time I ran it:
```
Traceback (most recent call last):
  File "/var/lib/os2borgerpc/jobs/150534/executable", line 124, in <module>
    os.mkdir(db_path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/chrome/snap/chromium/common/chromium/Default/Local Storage/'
>>> Failed with exit status 1 at 2021-04-26 08:57:25.385836
```

I think this is because the script uses `os.mkdir` and _not_ `os.makedirs`: the former can't create `a/b/c/` if either `a/` or `a/b/` is missing.

(Does this actually work, even in theory, though? Don't we run the risk that Chromium will look for a file that doesn't exist, conclude that the profile is corrupt, and replace it with a fresh one?)

**Comment by magenta-mfm** [comment]
Since it succeeded the second time without any changes(?) I'm inclined to think that Plyvel's `create_if_missing` argument to the DB creates the parent directories as needed, and so we can simply delete the mkdir line from the script?
That argument is documented here, but they don't specify what it does in case of missing parent dirs:
https://plyvel.readthedocs.io/en/latest/api.html#database

It's not something I've changed from the previous version of the script, though, so at least it used to work.
I'd think Chromium's profile has been initialized in terms of strictly needed files earlier in the script, when its launched with Selenium.

**Comment by magenta-mfm** [comment]
Well, that idea of mine did not work:
`plyvel._plyvel.Error: b'NotFound: /home/chrome/snap/chromium/common/chromium/Default/Local Storage/leveldb//LOCK: No such file or directory'`

...so went with yours, tried deleting its immediate parent directory (Local Storage) and it still worked.
But with your scenario I wonder how many levels of parent dirs were missing.

**Comment by magenta-mfm** [comment]
Merged since the requested changes were made and the related issue was closed.

**Pull request merged**
